### ISSUE TITLE
Default value not handled by the datepicker

### ISSUE THREAD

**Issue by sylouuu** [alongubkin/angular-datepicker#40]
Specify a default such as: `$scope.myDate = '2015-01-01';`

The datepicker is still pointing on today.

[Demo](http://plnkr.co/edit/HoLimeMkaiXqHkXXHLlL?p=preview)

Bests

**Comment by windmaomao** [comment]
@willks, I believe the code is two way binding, but it wasn't monitoring the change of the value afterwards.

**Comment by windmaomao** [comment]
ok, i really hate the code is grunted, so i don't really know how to extend the code other than just add the following two lines 

            scope.$watch('pickADate', function() {
                element.pickadate('picker').set('select', scope.pickADate);

            });

**Comment by windmaomao** [comment]
Well for whatever reason, I couldn't get it working, so I just go back to the pickadate.js and then add the following directive (which is just the simplified version), and it worked. So there must be some bug in the current code.

    app.directive('pickADate', function() {
        return {
            restrict: 'A',
            scope: {
                pickADate: '=',
                pickADateOptions: '='
            },
            link: function(scope, elem, attrs) {
    
                elem.pickadate();
    
                setTimeout(function() {
                    if (scope.pickADate) {
                        elem.pickadate('picker').set('select', scope.pickADate);
                    }
                }, 1000);
    
                scope.$watch('pickADate', function() {
                    elem.pickadate('picker').set('select', scope.pickADate);
                });
            }
        }
    });

**Comment by jonathan-reisdorf** [comment]
works for me if my initial date is (whyever) a javascript date object.
anyway, code should be improved to get rid of the timeout and only use scope.$watch -> see here: https://github.com/jonathan-reisdorf/angular-datepicker/commit/f89b770cd45504294cfc9c7ac4ce4defd2b3139d

**Comment by shahroon** [comment]
Works fine if we set default date as,
pick-a-date="startDate"  //startDate as $scope variable with whatever default date you want to
and set date format as,
$scope.options = {
                    format: 'yyyy-mm-dd'
                };
at controller end.
