### ISSUE TITLE
Is this hub dead?

### ISSUE THREAD

**Issue by maxcook** [alongubkin/angular-datepicker#54]
@alongubkin do you still support this project?

**Comment by alongubkin** [comment]
No, sorry.

**Comment by enricodeleo** [comment]
Is there any valid alternative to this project?

**Comment by Toilal** [comment]
I've created a project [ng-pickadate](https://github.com/Toilal/ng-pickadate). It has the JQuery dependency, but it's working properly and maintained as it's only a wrapper on [pickadate.js](http://amsul.ca/pickadate.js/).

**Comment by maxcook** [comment]
@Toilal unfortunately jQuery is a no go ...

**Comment by wannymiarelli** [comment]
Actually, and this is a lil off-topic, i doubt there is a way to exclude jQuery from medium-big size project. I started with " no jquery " but ended using it.
Excuse me for typo.

**Comment by rvanbaalen** [comment]
Please remove this project from the bower repository if you're no longer maintaining it. This keeps the repo from polluting @alongubkin

**Comment by romaintb** [comment]
Yes please, or transfer ownership, anyone willing to maintain the repo ? :)

**Comment by geoidesic** [comment]
I haven't maintained a repo before... so not too sure what it all entails but I'm willing.
I use this widget in production and I think it's really good.

**Comment by alongubkin** [comment]
@geoidesic I've added you as a collaborator. Thanks!

**Comment by rvanbaalen** [comment]
Just help and maintain the angular ui datepicker repo. Widely used.

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.
